CPU_NAME = "Intel Xeon"
CPU_NUMBER = "E5-2630V4"
CPU_BASE_FRQ = "2.2 GHz"
CPU_MAX_FRQ = "3.1 GHz"
TURBO_BOOST = "Disabled"
L1_CACHE = "192 KiB"
L2_CACHE = "24 MiB"
L3_CACHE = "16 MiB"
WRITE_BANDWIDTH = "TODO"
READ_BANDWIDTH = "TODO"

info_list = [
    CPU_NAME,
    CPU_NUMBER,
    CPU_BASE_FRQ,
    CPU_MAX_FRQ,
    TURBO_BOOST,
    L1_CACHE,
    L2_CACHE,
    L3_CACHE,
    # WRITE_BANDWIDTH,
    # READ_BANDWIDTH
]
