CPU_NAME = "Intel (Whiskey Lake)"
CPU_NUMBER = "i5-8265U"
CPU_BASE_FRQ = "1.8 GHz"
CPU_MAX_FRQ = "3.9 GHz"
TURBO_BOOST = "Disabled"
L1_CACHE = "128 KiB"
L2_CACHE = "1 MiB"
L3_CACHE = "6 MiB"
WRITE_BANDWIDTH = "TODO"
READ_BANDWIDTH = "TODO"

info_list = [
    CPU_NAME,
    CPU_NUMBER,
    CPU_BASE_FRQ,
    CPU_MAX_FRQ,
    TURBO_BOOST,
    L1_CACHE,
    L2_CACHE,
    L3_CACHE,
    # WRITE_BANDWIDTH,
    # READ_BANDWIDTH
]
