# CSV columns
BINARY = "Binary"
FLAGS = "Flags"
PARAM_N = "N"
PARAM_M = "M"
PARAM_T = "T"
NUM_ITERATIONS = "Iterations"
NUM_CYCLES = "Cycles"
NUM_FLOPS = "Flops"
DATA_MOVEMENT = "DATA_MOVEMENT"
PERFORMANCE = "Performance"
MEMORY_BANDWIDTH = "BANDWIDTH"
SECTION = "Section"
COMPILER = "Compiler"
VARIABLE = "Variable"
CACHE_MISS = "Cache Miss"
CACHE_ACCESS = "Cache Access"
MISS_RATE = "Miss Rate"
